### ISSUE TITLE
Extra scrollbar in content section

### ISSUE THREAD

**Issue by jeffschuler** [cuyahoga-tap/cuyasurvey-drupal#11]
In the content section of the form (below the header and above the footer) an extra scrollbar appears.

Because of the following in jquery.mobile-1.0.css:

``` CSS
.ui-content {
    overflow-y: visible;
}
```
